Transform: AWS::Serverless-2016-10-31
Description: 영상 썸네일 이미지 추출 애플리케이션

Resources:
  ThumbnailGenerator:
    Type: AWS::Serverless::Function

    Metadata:
      Dockerfile: ./dockerfiles/Dockerfile
      DockerContext: ../

    Properties:
      FunctionName: ThumbnailGenerator
      Runtime: python:3.9
      PackageType: Image
      Timeout: 600
      MemorySize: 1024      
      Events:
        VideoUpload:
          Type: S3
          Properties:
            Bucket: AWS::S3::Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .mp4
      
    