# 경량 Ubuntu 이미지 사용
FROM ubuntu:latest

RUN apt-get update && apt-get install -y && python3 && python3-pip

RUN pip3 install awscli
RUN pip3 install aws-sam-cli

COPY ./scripts/ /scripts/
COPY ./localstack/ /localstack/

RUN chmod +x /scripts/local_aws_s3_setup.sh

ENTRYPOINT []
CMD ["/scripts/local_aws_s3_setup.sh"]
