Transform: AWS::Serverless-2016-10-31
Description: 영상 업로드 애플리케이션

Resources:
  VideoUploader:
    Type: AWS::Serverless::Function

    Properties:
      FunctionName: VideoUploader
      Runtime: python3.9
      PackageType: Zip
      CodeUri: ../app
      Handler: src.main.lambda_handler
      Timeout: 600
      MemorySize: 1024
      Tracing: Active
      Environment:
        Variables:
          AWS_REGION_NAME: ap-northeast-2       
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_ENDPOINT_URL: http://localhost:4566
      Events:
        UploadVideo:
          Type: HttpApi
          Properties:
            Path: /video/upload
            Method: get
            ApiId: !Ref UploadVideoAPI

  UploadVideoAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: test
      CorsConfiguration: 
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "Access-Control-Allow-Origin"
          - "Content-Type"
          - "X-Requested-With"
        AllowMethods:
          - GET
