Transform: AWS::Serverless-2016-10-31
Description: 영상 업로드 애플리케이션

Resources:
  VideoUploader:
    Type: AWS::Serverless::Function

    Properties:
      FunctionName: VideoUploader
      Runtime: python:3.9
      PackageType: Zip
      CodeUri: app/
      Handler: src.main.lambda_handler
      Timeout: 600
      MemorySize: 1024
      Events:
        APIGateway:
          Type: Api
          Properties:
            Path: /video
            Method: POST
      Environment:
        Variables:
          LEVEL: LEVEL
          AWS_REGION_NAME: AWS_REGION        
          AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
          AWS_ENDPOINT_URL: AWS_ENDPOINT_URL
