name: Deploy serverless applications to AWS with SAM
on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      changed-count: ${{ steps.get-changed-application.outputs.changed-count }}
      changed-application: ${{ steps.get-changed-application.outputs.changed-application }}
    steps:
      - name: Checkout GitHub
        uses: actions/checkout@v2

      - name: Get changed application
        id: get-changed-application
        run: |
          chmod +x ./scripts/check-deploy-application.sh
          ./scripts/check-deploy-application.sh       

  deploy:
      needs: prepare
      if: ${{ needs.prepare.outputs.changed-count == '1' }}
      runs-on: ubuntu-latest  
      steps:
        - name: Checkout GitHub
          uses: actions/checkout@v2
                
        - name: Set up Python
          uses: actions/setup-python@v2
        
        - name: Install AWS SAM CLI
          uses: aws-actions/setup-sam@v1

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Build serverless applicatio with SAM
          run: sam build -t ./templates/template.yaml
          working-directory: ${{ needs.prepare.outputs.changed-application }}

        - name: Deploy serverless application with AWS
          run: sam deploy -t .aws-sam/build/template.yaml
          working-directory: ${{ needs.prepare.outputs.changed-application }}
